### ISSUE TITLE
feedback: porting github.com/vmware/vmw-guestinfo

### ISSUE THREAD

**Issue by sigma** [mmcloughlin/avo#132]
Hi,

I spent a bit of time porting https://github.com/vmware/vmw-guestinfo to avo (current draft: https://github.com/sigma/vmw-guestinfo/commit/b58ba65f2982ce909c21ecc21fa700fb1fe0b6cc), and hit a few limitations that might be worth mentioning.

1. some missing instructions. Turns out that i/o port operations are not mapped. Specifically I needed `INL/INSB/OUTSB` but as far as I can tell the entire set is missing. Also, the REP family of prefixes seems missing too. Probably because they're not mapped in internal/data/x86_64.xml ?

1. To work around the above, I decided to use [Instruction()](https://godoc.org/github.com/mmcloughlin/avo/build#Context.Instruction) to provide my own implementation. But the fact that this helper is not exposed as a top-level function like the rest kinda got in the way, forcing me to use an explicit Context instead of the global one (nothing critical, but I don't think there's a good reason for that?). In particular, TEXT() is also out of reach, so the result looks a bit less like asm than I'd like.

1. I needed to generate different implementations for amd64 and 386. At some point I realized that the alignment of the return values in 386 was off, and that was because of https://github.com/mmcloughlin/avo/blob/master/gotypes/components.go#L16
So I added my own command-line flag to specify the arch, and set gotypes.Sizes accordingly. It feels like there should be a better way to do that though (in particular to prevent changing this mid-generation I suppose).

I packaged all the workarounds together here in case you're interested: https://github.com/sigma/vmw-guestinfo/blob/b58ba65f2982ce909c21ecc21fa700fb1fe0b6cc/internal/gen.go

Other than that, it was pretty smooth, and despite the asm there being extremely small I found a bug in the initial hand-crafted code...
So thank you !

**Comment by mmcloughlin** [comment]
@sigma Really cool to see you using this, and thanks for taking the time to share your feedback!

 1. Yes the string instructions are missing, mainly because they are missing from the opcodes database I used (as you correctly identified). Since you're now the second person to ask for them, I'll try to prioritize #99.

2. The reason for not exposing `Instruction()` at the global scope is because generally you'd be strongly discouraged from using `Instruction()` yourself, since it's very easy to misuse. Since you appear to be doing manual register allocation in your code this is less of an issue, but typically you'd have to ensure the instruction input/outputs and control flow flags are correctly set, as the "compiler passes" rely on these properties for register allocation.
https://github.com/mmcloughlin/avo/blob/fb157e1de836bf0660e167f46a54e50b9289f6b9/ir/ir.go#L38-L48
That said, one solution that still provides an escape hatch for "power users" like yourself would be to export the global context as a public variable, like `http.DefaultServeMux`. This way you could use the assembly-like functions most of the time, but access other functions through the global context if you really needed to. Or of course, I could just expose every single `Context` method as a function #33. Created #133.

3. Unfortunately I didn't prioritize `386` architecture support, so this is probably not the only thing that's broken. I've made a proposal issue #134.

Thanks again.
