### ISSUE TITLE
"wrong argument size" for uint16 arguments

### ISSUE THREAD

**Issue by ericlagergren** [mmcloughlin/avo#191]
This snippet will cause compilation errors: `foo: wrong argument size 8; expected $...-2`

```
TEXT("foo", 0, "func(x uint16)")
RET()
```

**Comment by mmcloughlin** [comment]
Okay, #212 reproduces the bug. To clarify, it seems to be an `asmdecl` error not a compilation error.

So I'm pretty sure I've found the bug. If there are return values then the arguments structure is padded to max alignment before the first return value. `avo` is doing the padding even if there are no return values, as in this case. See on the `avo` side:

https://github.com/mmcloughlin/avo/blob/1d235fb56e3541a42dcee7bd2278cf912302a24b/gotypes/signature.go#L102

And in `asmdecl`:

https://github.com/golang/tools/blob/351c04c5a14afe1131e549831fcb29a0ca1df982/go/analysis/passes/asmdecl/asmdecl.go#L627

Fix should be simple, but I'm wondering about how to create a test suite that would more thoroughly test these issues, because #195 seems to be another instance.

**Comment by mmcloughlin** [comment]
I believe this is fixed, with an extensive test added in #216. Tagged release v0.3.1.
