### ISSUE TITLE
question: how to cast RCX to CL?

### ISSUE THREAD

**Issue by gevg** [mmcloughlin/avo#52]
I want to use the lower 8 bits of RCX as an operand in a SHLQ operation.
My subroutine has a variable that uses the RCX register. How can I cast this variable or create a new variable that uses the lower 8 bits of RCX? I guess this is supported but I cannot find how to do it?.

**Comment by mmcloughlin** [comment]
Thanks for filing this issue.

`As8()` will cast a general-purpose register to the corresponding low 8-bit register. The [tests/cast/asm.go](https://github.com/mmcloughlin/avo/blob/master/tests/cast/asm.go) test shows how this works.

Are you using `RCX` directly, or are you using a general-purpose 64-bit register? I am concerned that due to virtual registers, the register allocator will not currently do the right thing. Issue #19 covers the work to handle instructions that require fixed register inputs. If this is the case, your best short-term fix would be to use a physical register for the shift amount. Thankfully the register allocator does allow you to mix-and-match physical and virtual registers in the same function.

**Comment by mmcloughlin** [comment]
Did this solve your problem?

**Comment by mmcloughlin** [comment]
Closing since I haven't heard back, please reopen if you have more questions. Remaining work in this area is covered by #19.
