### ISSUE TITLE
reg: same physical register for two different virtual registers

### ISSUE THREAD

**Issue by etiennedaspe** [mmcloughlin/avo#76]
Hello, I'm currently trying to implement md5 with avo (just to learn), and I found this strange behavior.

```
// some code

a, b, c, d := GP32(), GP32(), GP32(), GP32()

// some other code

t := GP32()
MOVL(a, t)
```
In this case, a and t will have the same physical register (not expected), so the MOVL instruction will look like this for example: 
`MOVL DI, DI`

But if I duplicate the MOVL instruction, a and t will have two different physical registers.
```
// some code

a, b, c, d := GP32(), GP32(), GP32(), GP32()

// some other code

t := GP32()
MOVL(a, t)
MOVL(a, t)
```
The two MOVL instructions will look like this:
`MOVL DI, R12`
`MOVL DI, R12`

I didn't manage to reproduce the problem in a simpler example, so here is my code:
https://github.com/etiennedaspe/md5-avo/blob/bd5eb593cc060a5f687d7f08604f2cab89fcb10e/asm.go

The initialization of 'a' is on line 28, and the initialization of 't' and the MOVL instruction are on lines 88-89.

**Comment by mmcloughlin** [comment]
@etiennedaspe Thanks for filing the issue. MD5 is a great example to learn on :)

I definitely agree this is odd and sub-optimal behavior, but can you confirm if it's producing incorrect code?

The reason I ask is the SHA-1 code (similar to your MD5) uses subroutines for structure. This sometimes means you need to use temporary registers which may not be required otherwise. I'm speculating that you have a situation like this, in which case liveness analysis and the register allocator can effectively discover that the temporary register isn't necessary and reuse the same register. If this is happening, there's a chance that the code is still correct even though the move instructions are redundant.

**Comment by dgryski** [comment]
I've definitely seen this happen with PeachPy, so it wouldn't surprise me to see it with avo.  My suggestion is to have an optional cleanup pass (like the "remove jmp to immediately following label") that removes these extra REG/REG moves.

**Comment by etiennedaspe** [comment]
@mmcloughlin It produces correct code indeed, and it seems to be linked with the subroutine I use you're right (and actually your SHA-1 implementation is my biggest source of inspiration 😉)

**Comment by mmcloughlin** [comment]
Thanks for confirming @etiennedaspe!

Somewhat reassuring that this occurs in PeachPy too. I think a "cleanup pass" is the right approach @dgryski .

**Comment by mmcloughlin** [comment]
In preparation for implementing a fix, I've put together a simple reproducer. The following implements addition with an "avo subroutine".

https://github.com/mmcloughlin/avo/blob/4ad70b5de4b15aa48eb301558a534ba6294d16a1/tests/fixedbugs/issue76/asm.go#L10-L25

Note it's natural to create a temporary for the result. However this ends up producing a redundant move.

https://github.com/mmcloughlin/avo/blob/4ad70b5de4b15aa48eb301558a534ba6294d16a1/tests/fixedbugs/issue76/issue76.s#L6-L12

**Comment by mmcloughlin** [comment]
#80 should addresses this problem. Any code review appreciated :)
